# Generated by Django 3.2.12 on 2022-02-07 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('logo_brand', models.ImageField(blank=True, null=True, upload_to='brand_logo/')),
            ],
            options={
                'verbose_name': 'Product Brand',
                'verbose_name_plural': 'Product Brands List',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='product title')),
                ('main_image', models.ImageField(blank=True, help_text='main image of the current product', null=True, upload_to='product_images_main/', verbose_name='main image')),
                ('short_description', models.CharField(max_length=500, verbose_name='product short description')),
                ('description', models.TextField(verbose_name='product description')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='product added date')),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
                ('sell_count', models.IntegerField(blank=True, default=0, help_text='Number of product sales', null=True)),
                ('visited_count', models.IntegerField(default=0, help_text='number of visited this product')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.category', verbose_name='product category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product List',
            },
        ),
        migrations.CreateModel(
            name='Visited_Ip_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.TextField(help_text='user ip address', verbose_name='ip address')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.product')),
            ],
            options={
                'verbose_name': 'ip address',
                'verbose_name_plural': 'users ip address',
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, verbose_name='product price')),
                ('discount_price', models.FloatField(blank=True, help_text='discount price for a product', null=True, verbose_name='product discount price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products_image/', verbose_name='product image')),
                ('is_active', models.BooleanField(default=False, verbose_name='product activation')),
                ('quantity', models.IntegerField(help_text='number of current product', verbose_name='product quantity')),
                ('color', models.CharField(max_length=100, verbose_name='product color')),
                ('size', models.CharField(max_length=100, verbose_name='product size')),
                ('product', models.ForeignKey(help_text='product that related to the current detail', on_delete=django.db.models.deletion.CASCADE, to='product_module.product')),
            ],
            options={
                'verbose_name': 'Product Details',
                'verbose_name_plural': 'Product Details List',
            },
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product')),
            ],
            options={
                'verbose_name': 'product comment',
                'verbose_name_plural': 'product comment list',
                'ordering': ['created_date'],
            },
        ),
    ]
