# Generated by Django 4.0 on 2021-12-25 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='product title')),
                ('short_description', models.CharField(max_length=500, verbose_name='product short description')),
                ('description', models.TextField(verbose_name='product description')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='product added date')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product List',
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, verbose_name='product price')),
                ('discount_price', models.FloatField(blank=True, help_text='discount price for a product', null=True, verbose_name='product discount price')),
                ('is_active', models.BooleanField(default=False, verbose_name='product activation')),
                ('quantity', models.IntegerField(help_text='number of current product', verbose_name='product quantity')),
                ('color', models.CharField(max_length=100, verbose_name='product color')),
                ('size', models.CharField(max_length=100, verbose_name='product size')),
                ('product', models.ForeignKey(help_text='product that related to the current detail', on_delete=django.db.models.deletion.CASCADE, to='product_module.product')),
            ],
        ),
    ]
