# Generated by Django 4.0 on 2021-12-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_alter_category_options_product_sell_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products_image/', verbose_name='product image'),
        ),
    ]
