# Generated by Django 4.0 on 2021-12-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_productdetail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, help_text='main image of the current product', null=True, upload_to='', verbose_name='main image'),
        ),
    ]
