# Generated by Django 4.0 on 2021-12-26 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0009_brand_productdetail_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='brand',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.brand'),
        ),
    ]
