# Generated by Django 4.0 on 2021-12-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0011_remove_product_categories_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo_brand',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
