# Generated by Django 4.0 on 2021-12-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0012_brand_logo_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo_brand',
            field=models.ImageField(blank=True, null=True, upload_to='brand_logo/'),
        ),
    ]
