# Generated by Django 4.0 on 2021-12-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0013_alter_brand_logo_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, help_text='main image of the current product', null=True, upload_to='product_images_main/', verbose_name='main image'),
        ),
    ]
