# Generated by Django 4.0 on 2021-12-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0015_productcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visited_count',
            field=models.IntegerField(default=0, help_text='number of visited this product'),
        ),
    ]
