# Generated by Django 4.0 on 2021-12-31 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0016_product_visited_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visited_Ip_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.TextField(help_text='user ip address', verbose_name='ip address')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'ip address',
                'verbose_name_plural': 'users ip address',
            },
        ),
    ]
