# Generated by Django 4.0 on 2022-01-02 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'province',
                'verbose_name_plural': 'provinces',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False, help_text='order paid or not')),
                ('is_send', models.BooleanField(default=False, help_text='order sent or not')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='created current user order')),
                ('payment_date', models.DateTimeField(blank=True, help_text='order payment date', null=True)),
                ('tracking_code', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('family', models.CharField(max_length=50, null=True)),
                ('post_code', models.IntegerField(null=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('address', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order_module.city')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order_module.province')),
            ],
            options={
                'verbose_name': 'user order',
                'verbose_name_plural': 'orders list',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_module.province'),
        ),
    ]
