# Generated by Django 4.0 on 2022-01-02 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0018_alter_visited_ip_product_product'),
        ('order_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
            ],
            options={
                'verbose_name': 'discount code',
                'verbose_name_plural': 'coupon codes',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='قیمت محصول')),
                ('count', models.IntegerField(verbose_name='تعداد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_module.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product')),
                ('product_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.productdetail')),
            ],
            options={
                'verbose_name': 'product detail',
                'verbose_name_plural': 'product detail lists',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='order_module.coupon'),
        ),
    ]
