# Generated by Django 4.0 on 2022-01-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0004_alter_order_address_alter_order_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='price',
            field=models.IntegerField(),
        ),
    ]
